spring.application.name=studentCRUD
spring.datasource.url=jdbc:postgresql://localhost:5432/studentdb
spring.datasource.username=postgres
spring.datasource.password=Prasoon@123
spring.datasource.driver-class-name=org.postgresql.Driver